### ISSUE TITLE
Can't drag and drop images from explorer to Quiver

### ISSUE THREAD

**Issue by nm17** [DeflatedPickle/Quiver#39]
**Describe the bug**
Can't drag and drop images from explorer to Quiver 
Version: 1.5.0

**To Reproduce**
Steps to reproduce the behaviour:
1. Open some texture pack
2. Drag and drop a file to the File Table

**Expected behaviour**
A file should be added along side other files.

**Screenshots**
https://www.youtube.com/watch?v=mlMZAW3nQFo

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10 2004

**Additional context**
```
java.lang.NullPointerException: destination
	at java.util.Objects.requireNonNull(Objects.java:228)
	at org.apache.commons.io.FileUtils.validateMoveParameters(FileUtils.java:2648)
	at org.apache.commons.io.FileUtils.moveFileToDirectory(FileUtils.java:2043)
	at com.deflatedpickle.quiver.filetable.FileTable$addDropTarget$1.drop(FileTable.kt:115)
	at sun.awt.dnd.SunDropTargetContextPeer.processDropMessage(SunDropTargetContextPeer.java:538)
	at sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchDropEvent(SunDropTargetContextPeer.java:852)
	at sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchEvent(SunDropTargetContextPeer.java:776)
	at sun.awt.dnd.SunDropTargetEvent.dispatch(SunDropTargetEvent.java:48)
	at java.awt.Component.dispatchEventImpl(Component.java:4744)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processDropTargetEvent(Container.java:4609)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4471)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by DeflatedPickle** [comment]
Sorry that I took so long to get to this. I needed a break
