### ISSUE TITLE
array element type mismatch

### ISSUE THREAD

**Issue by AstroOrbis** [DeflatedPickle/Quiver#95]
stroOrbis@astrospcomputer Quiver-1.10.0 % ./Quiver
[DEBUG] 20:30:23 (500 ms since JVM launch) [main/1] com.deflatedpickle.quiver.launcher.MainKt: Installed JANSI for this terminal session
	com.deflatedpickle.quiver.launcher.MainKt.main(main.kt:45)
[INFO ] 20:30:23 (606 ms since JVM launch) [main/1] com.deflatedpickle.quiver.launcher.MainKt:
OS  : MAC (mac os x)
Java: null (null)
Dir : /Users/AstroOrbis/Desktop/Quiver-1.10.0
Dev?: false
	com.deflatedpickle.quiver.launcher.MainKt.main(main.kt:52)
[DEBUG] 20:30:24 (1297 ms since JVM launch) [main/1] com.deflatedpickle.quiver.launcher.MainKt: Registered a default exception handler
	com.deflatedpickle.quiver.launcher.MainKt.main(main.kt:99)
[INFO ] 20:30:24 (1313 ms since JVM launch) [main/1] com.deflatedpickle.quiver.launcher.MainKt: Created the plugins folder at /Users/AstroOrbis/Desktop/Quiver-1.10.0/plugins
	com.deflatedpickle.quiver.launcher.MainKt.main(main.kt:106)
[INFO ] 20:30:24 (1321 ms since JVM launch) [main/1] ClassGraphUtil: Found the plugin JARs: [swingsettings-1.0.0.jar, markdownviewer-1.0.0.jar, zipstep-1.0.0.jar, launcher-1.0.0.jar, imageviewer-1.0.0.jar, tipoftheday-1.0.0.jar, textviewer-1.0.0.jar, pluginmanager-1.0.2.jar, spritesheetviewer-1.0.0.jar, core-1.3.0.jar, treeviewer-1.0.0.jar, tableviewer-1.0.0.jar, foldertree-1.0.0.jar, filepanel-1.0.0.jar, packexport-1.0.0.jar, settingsgui-1.1.1.jar, master-1.10.0.jar, packsquashstep-1.0.0.jar, filetable-1.0.1.jar]
	com.deflatedpickle.haruhi.util.ClassGraphUtil.<clinit>(ClassGraphUtil.kt:29)
[DEBUG] 20:30:24 (1477 ms since JVM launch) [main/1] com.deflatedpickle.haruhi.util.PluginUtil: Found the plugin ImageViewerPlugin from com.deflatedpickle.imageviewer
	com.deflatedpickle.haruhi.util.PluginUtil.discoverPlugins(PluginUtil.kt:118)
[WARN ] 20:30:24 (1478 ms since JVM launch) [main/1] com.deflatedpickle.quiver.launcher.MainKt: main threw java.lang.IllegalArgumentException: array element type mismatch
	com.deflatedpickle.quiver.launcher.MainKt$main$2.uncaughtException(main.kt:83)
[DEBUG] 20:30:28 (5713 ms since JVM launch) [Thread-0/24] com.deflatedpickle.quiver.launcher.MainKt: Uninstalled JANSI for this terminal session
	com.deflatedpickle.quiver.launcher.MainKt$main$1.run(main.kt:69)
[DEBUG] 20:30:28 (5714 ms since JVM launch) [Thread-0/24] com.deflatedpickle.quiver.launcher.MainKt: The JVM instance running Quiver was shutdown
	com.deflatedpickle.quiver.launcher.MainKt$main$1.run(main.kt:72)

**Comment by DeflatedPickle** [comment]
This is a frequent issue related to not using Java 8, as seen in #40 and #45. I do say in the [README](https://github.com/DeflatedPickle/Quiver/blob/561417b8f6551426dc528393e68a9167093a2039/README.md#L17) to use specifically Java 8! Versions supporting newer Java versions are planned, however due to the issues seen [here](https://github.com/DeflatedPickle/Quiver/actions/runs/941514251), there's some porting needed first

**Comment by AstroOrbis** [comment]
I installed java8 using `brew tap adoptopenjdk/openjdk && brew install --cask adoptopenjdk8` but it still gives the same error.

**Comment by DeflatedPickle** [comment]
Try running `java -version`. It sounds like you haven't changed your `JAVA_HOME`

**Comment by AstroOrbis** [comment]
You're right...

AstroOrbis@astrospcomputer ~ % java -version
openjdk version "15.0.2" 2021-01-19
OpenJDK Runtime Environment (build 15.0.2+7-27)
OpenJDK 64-Bit Server VM (build 15.0.2+7-27, mixed mode, sharing)

How would I change my JAVA_HOME?

**Comment by AstroOrbis** [comment]
Nevermind, I found it!

**Comment by DeflatedPickle** [comment]
Awesome! I hope you find Quiver helpful, but if you come across any quirks or wish there was a certain feature, please open new issues for them. I want as much user feedback as I can get

**Comment by AstroOrbis** [comment]
Allright!

**Comment by AstroOrbis** [comment]
Well crap, I installed and set JAVA_HOME using [this](https://stackoverflow.com/questions/21964709/how-to-set-or-change-the-default-java-jdk-version-on-macos) but it still gives me a (different) error:

java.lang.ExceptionInInitializerError
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:156)
	at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
	at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
	at java.lang.reflect.Field.get(Field.java:393)
	at kotlin.reflect.jvm.internal.KClassImpl$Data$objectInstance$2.invoke(KClassImpl.kt:117)
	at kotlin.reflect.jvm.internal.ReflectProperties$LazyVal.invoke(ReflectProperties.java:62)
	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31)
	at kotlin.reflect.jvm.internal.KClassImpl$Data.getObjectInstance(KClassImpl.kt)
	at kotlin.reflect.jvm.internal.KClassImpl.getObjectInstance(KClassImpl.kt:242)
	at com.deflatedpickle.haruhi.util.PluginUtil.loadPlugins(PluginUtil.kt:145)
	at com.deflatedpickle.quiver.launcher.MainKt.main(main.kt:141)
Caused by: java.lang.IllegalArgumentException: cannot add to layout: unknown constraint: LEFT
	at java.awt.BorderLayout.addLayoutComponent(BorderLayout.java:463)
	at java.awt.BorderLayout.addLayoutComponent(BorderLayout.java:424)
	at java.awt.Container.addImpl(Container.java:1130)
	at java.awt.Container.add(Container.java:975)
	at org.jdesktop.swingx.prompt.BuddySupport.addToComponentHierarchy(BuddySupport.java:72)
	at org.jdesktop.swingx.prompt.BuddySupport.ensureBuddiesAreInComponentHierarchy(BuddySupport.java:139)
	at org.jdesktop.swingx.plaf.TextUIWrapper$DefaultWrapper.replaceUIIfNeeded(TextUIWrapper.java:162)
	at org.jdesktop.swingx.plaf.TextUIWrapper.install(TextUIWrapper.java:49)
	at org.jdesktop.swingx.JXSearchField.setUseNativeSearchFieldIfPossible(JXSearchField.java:519)
	at org.jdesktop.swingx.JXSearchField.<init>(JXSearchField.java:176)
	at com.deflatedpickle.quiver.frontend.widget.SearchToolbar.<init>(SearchToolbar.kt:20)
	at com.deflatedpickle.quiver.filetable.FileTablePlugin.<clinit>(FileTablePlugin.kt:40)
	... 13 more


...Now what?

**Comment by DeflatedPickle** [comment]
So, this error is saying that Swing doesn't have a `LEFT` constant. I don't have a solution for that. I've never seen this

**Comment by AstroOrbis** [comment]
Well crap. Do I try running Quiver in a VM? I just uninstalled all versions of Java on my computer and reinstalled JRE/JDK 8.

**Comment by DeflatedPickle** [comment]
You could, I guess, or you could clone Quiver, initialize the submodules, open it in an IDE, fix the issue happening in the `haruhi` submodule (maybe `LEFT` can be replaced by `LINE_START`?), fix any further errors and PR the changes to [haruhi](https://github.com/DeflatedPickle/haruhi). If your JDK is missing that `LEFT` constant, I can't test what can be used instead, as it might also be missing for you. Sorry about that
